import { AccountSignOut } from "@/components/account-sign-out";
import { GuardianAbsenceNoteForm } from "@/components/guardian-absence-note-form";
import type { GuardianPortalData } from "@/lib/guardian-portal-data";
import { formatGMTDate } from "@/lib/timezone";

export function GuardianPortalWorkspace({ data }: { data: GuardianPortalData }) {
  const schoolCount = new Set(data.students.map(student => student.schoolId)).size;
  return <main className="min-h-screen bg-slate-50 text-slate-900">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 bg-white px-5 py-5 sm:px-8">
      <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center bg-blue-700 text-lg font-bold text-white">K</span><div><p className="font-bold">Klassa · Family portal</p><p className="text-sm text-slate-500">Welcome, {data.guardianName}</p></div></div><AccountSignOut />
    </header>
    <div className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8">
      <section><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Family overview</p><h1 className="mt-1 text-2xl font-bold">Your students</h1><p className="mt-2 text-sm text-slate-600">Attendance, published results, and school notices for students linked to your guardian account.</p></section>
      {data.students.length === 0 ? <section className="border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold">No student access is linked to this account</h2><p className="mt-2 text-sm text-amber-950">Ask the school office to confirm your guardian record and legal-responsibility link.</p></section> : <>
         <div className="grid gap-4 sm:grid-cols-2">{data.students.map(student => <article key={student.id} className="border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{student.schoolName}</p><h2 className="mt-1 text-lg font-bold">{student.firstName} {student.lastName}</h2></div><span className="border border-blue-200 bg-blue-50 px-2 py-1 text-xs text-blue-800">{student.studentNumber}</span></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Class</dt><dd className="mt-1 font-medium">{student.className}</dd></div><div><dt className="text-slate-500">Academic year</dt><dd className="mt-1 font-medium">{student.currentYearName ?? "Not set"}</dd></div><div><dt className="text-slate-500">Recent attendance</dt><dd className="mt-1 font-medium">{student.attendanceRate == null ? "No records" : `${student.attendanceRate}%`}<span className="block text-xs font-normal text-slate-500">Up to 30 records from the last 120 days</span></dd></div><div><dt className="text-slate-500">Published reports</dt><dd className="mt-1 font-medium">{student.reports.length}</dd></div></dl>
          <details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-sm font-semibold text-blue-800">View attendance and results</summary><div className="mt-4 space-y-5"><section><h3 className="text-sm font-semibold">Recent attendance</h3><ul className="mt-2 divide-y divide-slate-100 text-sm">{student.attendance.slice(0, 10).map((record, index) => <li key={`${record.date}-${index}`} className="flex justify-between gap-3 py-2"><span>{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${record.date}T00:00:00Z`))}</span><span className="font-medium capitalize">{record.status}{record.status === "late" && record.arrivalMinutesLate > 0 ? ` · ${record.arrivalMinutesLate} min` : ""}</span></li>)}{student.attendance.length === 0 && <li className="py-2 text-slate-500">No submitted attendance yet.</li>}</ul></section><section><h3 className="text-sm font-semibold">Published report cards</h3><div className="mt-2 space-y-3">{student.reports.map(report => <article key={report.id} className="border border-slate-200 p-3"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{report.termName}</strong><span className="text-sm text-slate-600">{report.overallPercentage == null ? "" : `${report.overallPercentage}%`}{report.gpa == null ? "" : ` · GPA ${report.gpa}`}</span></div><ul className="mt-2 space-y-2">{report.subjects.map((subject, index) => <li key={`${subject.subjectName}-${index}`} className="text-sm"><div className="flex justify-between gap-2"><span>{subject.subjectName}</span><span className="font-medium">{subject.letterGrade} · {subject.scorePercentage}%</span></div>{subject.comments && <p className="mt-1 text-xs text-slate-600">{subject.comments}</p>}</li>)}</ul></article>)}{student.reports.length === 0 && <p className="text-sm text-slate-500">No published report cards yet.</p>}</div></section></div></details>
          <section className="mt-4 border-t border-slate-100 pt-4"><h3 className="text-sm font-semibold">Absence notes</h3><ul className="mt-2 space-y-2 text-xs">{student.absenceNotes.slice(0, 5).map(note => <li key={note.id} className="flex justify-between gap-2"><span>{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${note.absenceDate}T00:00:00Z`))} · {note.reasonCategory.replaceAll("_", " ")}</span><span className="font-medium capitalize">{note.status}</span></li>)}{student.absenceNotes.length === 0 && <li className="text-slate-500">No absence notes submitted.</li>}</ul></section>
         </article>)}</div>
        <GuardianAbsenceNoteForm students={data.students} />
        <section className="border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">School notices</h2><p className="mt-1 text-sm text-slate-500">Published notices for your students{schoolCount > 1 ? " across their schools" : ""}.</p></div><div className="divide-y divide-slate-100">{data.announcements.map(notice => <article key={notice.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{notice.title}</h3><span className="text-xs text-slate-500">{notice.schoolName} · {notice.publishedAt ? formatGMTDate(notice.publishedAt) : ""}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{notice.content}</p></article>)}{data.announcements.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No published notices yet.</p>}</div></section>
      </>}
      <p className="text-center text-xs text-slate-500">This portal shows published school information only. Contact your school for corrections or access support.</p>
    </div>
  </main>;
}
