"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { CalendarCheck, ChevronRight, ClipboardList, GraduationCap, LayoutDashboard, Megaphone, Menu, UsersRound, X } from "lucide-react";
import { AccountSignOut } from "@/components/account-sign-out";
import { StudentCsvImport } from "@/components/student-csv-import";
import { StudentEnrollmentFlow } from "@/components/student-enrollment-flow";
import { correctOfficeAttendanceAction, markGuardianAbsenceNoteReviewedAction, reviewAndExcuseGuardianAbsenceAction, saveOfficeRecordAction } from "@/app/actions/office-actions";
import type { OfficeData } from "@/lib/office-data";
import type { SchoolCommand } from "@/lib/school-admin-policy";
import type { announcements } from "@/db/schema";

const tabs = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "students", label: "Students", icon: GraduationCap },
  { id: "guardians", label: "Guardians", icon: UsersRound },
  { id: "attendance", label: "Attendance follow-up", icon: CalendarCheck },
  { id: "imports", label: "CSV imports", icon: ClipboardList },
  { id: "notices", label: "Notices", icon: Megaphone },
] as const;
const field = "mt-1 block min-h-11 w-full border border-slate-300 bg-white px-3 py-2 text-sm focus:border-blue-600";
const primary = "min-h-11 bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
const secondary = "min-h-11 border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 disabled:opacity-50";
const words = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const str = (form: FormData, name: string) => String(form.get(name) ?? "");
type Editor = { kind: "student" | "guardian" | "guardian_link"; values?: Record<string, string | boolean | null> };

function Field({ label, name, type = "text", defaultValue, required = true }: { label: string; name: string; type?: string; defaultValue?: string | null; required?: boolean }) {
  return <label className="block text-sm font-medium">{label}<input name={name} type={type} defaultValue={defaultValue ?? ""} required={required} className={field} /></label>;
}
function Select({ label, name, choices, defaultValue }: { label: string; name: string; choices: { id: string; name: string }[]; defaultValue?: string }) {
  return <label className="block text-sm font-medium">{label}<select name={name} required defaultValue={defaultValue ?? ""} className={field}><option value="">Choose {label.toLowerCase()}</option>{choices.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;
}
function Card({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><h2 className="text-lg font-bold">{title}</h2>{action}</div><div className="p-5">{children}</div></section>;
}

export function OfficeWorkspace({ data, notices, section, date }: { data: OfficeData; notices: (typeof announcements.$inferSelect)[]; section: string; date: string }) {
  const router = useRouter();
  const [pending, start] = useTransition();
  const [message, setMessage] = useState("");
  const [query, setQuery] = useState("");
  const [mobileNav, setMobileNav] = useState(false);
  const [editor, setEditor] = useState<Editor | null>(null);
  const [showEnrollment, setShowEnrollment] = useState(false);
  const [attendanceClass, setAttendanceClass] = useState("");
  const current = tabs.find(tab => tab.id === section) ?? tabs[0];
  const year = data.years.find(row => row.isCurrent);
  const yearClasses = data.classes.filter(row => row.academicYearId === year?.id);
  const selectedAttendanceClass = yearClasses.some(row => row.id === attendanceClass) ? attendanceClass : yearClasses[0]?.id ?? "";
  const classOptions = yearClasses.map(row => ({ id: row.id, name: `${data.grades.find(grade => grade.id === row.gradeLevelId)?.name ?? "Grade"} / ${row.name}` }));
  const studentOptions = data.students.map(row => ({ id: row.id, name: `${row.firstName} ${row.lastName}` }));
  const guardianOptions = data.guardians.map(row => ({ id: row.id, name: `${row.firstName} ${row.lastName}` }));
  const name = (id: string) => { const row = data.students.find(item => item.id === id); return row ? `${row.firstName} ${row.lastName}` : "Unknown student"; };
  const guardianName = (id: string) => { const row = data.guardians.find(item => item.id === id); return row ? `${row.firstName} ${row.lastName}` : "Unknown guardian"; };
  const enrollment = (id: string) => data.enrollments.find(row => row.studentId === id && row.academicYearId === year?.id);
  const classLabel = (id?: string | null) => { const row = data.classes.find(item => item.id === id); return row ? `${data.grades.find(grade => grade.id === row.gradeLevelId)?.name ?? "Grade"} / ${row.name}` : "Unassigned"; };
  const today = new Date().toISOString().slice(0, 10);
  const activeRestrictions = (id: string) => data.restrictions.filter(row => row.studentId === id && row.isEnforced &&
    (row.prohibitPickup || row.prohibitDisclosure) && row.effectiveDate <= today && (!row.expirationDate || row.expirationDate >= today));
  const matches = (...values: unknown[]) => values.join(" ").toLowerCase().includes(query.toLowerCase());
  const submitted = data.sessions.filter(row => row.status === "submitted");
  const attendanceSession = data.sessions.find(row => row.classId === selectedAttendanceClass && row.period === "morning_roll_call");
  const attendanceRecords = data.records.filter(row => row.sessionId === attendanceSession?.id).sort((a, b) => name(a.studentId).localeCompare(name(b.studentId)));
  const save = (command: SchoolCommand) => start(async () => {
    setMessage("");
    const result = await saveOfficeRecordAction(command);
    setMessage(result.success ? "Saved successfully." : result.error);
    if (result.success) { setEditor(null); router.refresh(); }
  });
  const submit = (event: React.FormEvent<HTMLFormElement>, make: (form: FormData) => SchoolCommand) => {
    event.preventDefault(); save(make(new FormData(event.currentTarget)));
  };
  const editStudent = (student: OfficeData["students"][number]) => setEditor({ kind: "student", values: {
    id: student.id, firstName: student.firstName, lastName: student.lastName,
    dateOfBirth: student.dateOfBirth, status: student.status, classId: enrollment(student.id)?.classId ?? "" } });
  const editGuardian = (guardian: OfficeData["guardians"][number]) => setEditor({ kind: "guardian", values: {
    id: guardian.id, firstName: guardian.firstName, lastName: guardian.lastName, email: guardian.email, phone: guardian.phone } });
  const editLink = (link: OfficeData["links"][number]) => setEditor({ kind: "guardian_link", values: {
    studentId: link.studentId, guardianId: link.guardianId, relationship: link.relationship,
    isPrimary: link.isPrimary, hasLegalResponsibility: link.hasLegalResponsibility } });
  return <div className="min-h-screen bg-slate-50 text-slate-900 lg:grid lg:grid-cols-[240px_minmax(0,1fr)]">
    <a href="#office-content" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-white focus:p-3">Skip to content</a>
    <aside className="border-b border-slate-800 bg-slate-950 text-slate-300 lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col"><div className="flex min-h-20 items-center justify-between border-b border-white/10 px-5"><Link href="/" className="flex items-center gap-3 text-white"><span className="grid h-9 w-9 place-items-center bg-blue-600 text-lg font-bold">K</span><span><strong className="block text-lg">Klassa</strong><small className="text-[10px] uppercase tracking-[.16em] text-slate-400">School office</small></span></Link><button className="grid h-11 w-11 place-items-center lg:hidden" aria-label={mobileNav ? "Close navigation" : "Open navigation"} aria-expanded={mobileNav} onClick={() => setMobileNav(!mobileNav)}>{mobileNav ? <X size={20} /> : <Menu size={20} />}</button></div>
      <nav className={`${mobileNav ? "block" : "hidden"} flex-1 p-3 lg:block`} aria-label="Office navigation">{tabs.map(tab => { const Icon = tab.icon; return <Link key={tab.id} href={`/?section=${tab.id}`} onClick={() => { setMobileNav(false); setQuery(""); setEditor(null); }} aria-current={current.id === tab.id ? "page" : undefined} className={`mb-1 flex min-h-11 items-center gap-3 px-3 text-sm font-medium ${current.id === tab.id ? "bg-blue-600 text-white" : "hover:bg-white/5 hover:text-white"}`}><Icon size={18} /><span className="flex-1">{tab.label}</span>{current.id === tab.id && <ChevronRight size={14} />}</Link>; })}</nav><div className="hidden border-t border-white/10 p-5 lg:block"><p className="text-sm font-semibold text-white">{data.actor.name}</p><p className="mt-1 text-xs">Office staff</p><Link href="/schools" className="mt-3 inline-flex min-h-11 items-center text-xs text-blue-300">Switch school</Link></div></aside>
    <div className="min-w-0"><header className="flex min-h-20 items-center justify-between gap-3 border-b border-slate-200 bg-white px-5 py-4 sm:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-blue-700">{year?.name ?? "No current school year"}</p><p className="mt-1 font-bold">{data.school.name}</p></div><AccountSignOut /></header>
      <main id="office-content" className="mx-auto max-w-[1400px] space-y-6 p-4 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-slate-500">School operations</p><h1 className="mt-1 text-2xl font-bold">{current.label}</h1></div>{["students", "guardians"].includes(current.id) && <label className="text-sm"><span className="sr-only">Search {current.label}</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder={`Search ${current.label.toLowerCase()}`} className={`${field} min-w-64`} /></label>}</div>
        {message && <p role="status" className="border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}
        {current.id === "overview" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
          { label: "Students", value: data.students.length, target: "students" },
          { label: "Pending intake", value: data.students.filter(row => row.status === "pending").length, target: "students" },
          { label: "Guardian contacts", value: data.guardians.length, target: "guardians" },
          { label: "Submitted roll calls", value: submitted.length, target: "attendance" },
        ].map(item => <Link key={item.label} href={`/?section=${item.target}`} className="border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{item.label}</p><p className="mt-3 text-3xl font-bold">{item.value}</p></Link>)}</div><div className="grid gap-5 xl:grid-cols-2"><Card title="Office tasks"><div className="space-y-3 text-sm">{[
          { label: "Review students awaiting intake", count: data.students.filter(row => row.status === "pending").length, target: "students" },
          { label: "Link guardians to students", count: data.students.filter(row => !data.links.some(link => link.studentId === row.id)).length, target: "guardians" },
          { label: "Call about unexplained absences", count: data.unexplainedAbsences.length, target: "attendance" },
        ].map(item => <Link key={item.target} href={`/?section=${item.target}`} className="flex min-h-11 items-center justify-between border-b border-slate-100"><span>{item.label}</span><strong>{item.count}</strong></Link>)}</div></Card><Card title="School notices">{notices.slice(0, 3).map(notice => <div key={notice.id} className="border-b border-slate-100 py-2 text-sm"><strong>{notice.title}</strong><p className="mt-1 text-slate-600">{notice.content}</p></div>)}{!notices.length && <p className="text-sm text-slate-500">No published notices.</p>}</Card></div></>}
        {current.id === "students" && <div className="space-y-5"><Card title="Student directory" action={<button className={primary} onClick={() => setShowEnrollment(true)}>Enroll student</button>}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-2">Student</th><th>Number</th><th>Current class</th><th>Guardians</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.students.filter(row => matches(row.firstName, row.lastName, row.studentNumber, row.externalReference)).map(student => { const restrictions = activeRestrictions(student.id); return <tr key={student.id} className="border-b border-slate-100"><td className="py-3"><strong>{student.firstName} {student.lastName}</strong>{restrictions.length > 0 && <span className="mt-1 block text-xs font-semibold text-amber-800">Pickup or disclosure restriction: check details before release</span>}</td><td>{student.studentNumber}{student.externalReference && <small className="block text-slate-500">Old ID: {student.externalReference}</small>}</td><td>{classLabel(enrollment(student.id)?.classId)}</td><td>{data.links.filter(link => link.studentId === student.id).map(link => guardianName(link.guardianId)).join(", ") || "None linked"}</td><td>{words(student.status)}</td><td><button className={secondary} onClick={() => editStudent(student)}>Edit</button></td></tr>; })}</tbody></table>{!data.students.length && <p className="py-4 text-sm text-slate-500">No students enrolled yet.</p>}</div></Card>
          {editor?.kind === "student" && <Card title={editor.values?.id ? "Edit student" : "Enroll student"} action={<button className={secondary} onClick={() => setEditor(null)}>Cancel</button>}><p className="mb-3 text-sm text-slate-600">Klassa assigns the student number when you save.</p><form key={String(editor.values?.id ?? "new")} className="grid gap-3 sm:grid-cols-2" onSubmit={event => submit(event, form => ({ kind: "student", ...(editor.values?.id ? { id: String(editor.values.id) } : {}), firstName: str(form, "firstName"), lastName: str(form, "lastName"), dateOfBirth: str(form, "dateOfBirth"), status: str(form, "status") as "pending", classId: str(form, "classId") }))}><Field label="First name" name="firstName" defaultValue={String(editor.values?.firstName ?? "")} /><Field label="Last name" name="lastName" defaultValue={String(editor.values?.lastName ?? "")} /><Field label="Date of birth" name="dateOfBirth" type="date" defaultValue={String(editor.values?.dateOfBirth ?? "")} /><Select label="Class in current year" name="classId" choices={classOptions} defaultValue={String(editor.values?.classId ?? "")} /><Select label="Status" name="status" choices={["pending", "active", "withdrawn", "graduated"].map(value => ({ id: value, name: words(value) }))} defaultValue={String(editor.values?.status ?? "pending")} /><button className={primary} disabled={pending || !year || !classOptions.length}>Save student</button></form>{(!year || !classOptions.length) && <p className="mt-3 text-sm text-amber-800">Ask the school administrator to create the current year and classes first.</p>}</Card>}</div>}
        {current.id === "guardians" && <div className="space-y-5"><Card title="Guardian contacts" action={<button className={primary} onClick={() => setEditor({ kind: "guardian" })}>Add guardian</button>}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-2">Name</th><th>Email</th><th>Phone</th><th>Linked students</th><th>Action</th></tr></thead><tbody>{data.guardians.filter(row => matches(row.firstName, row.lastName, row.email, row.phone)).map(guardian => <tr key={guardian.id} className="border-b border-slate-100"><td className="py-3 font-medium">{guardian.firstName} {guardian.lastName}</td><td>{guardian.email ?? "Not provided"}</td><td>{guardian.phone ?? "Not provided"}</td><td>{data.links.filter(link => link.guardianId === guardian.id).map(link => name(link.studentId)).join(", ") || "None"}</td><td><button className={secondary} onClick={() => editGuardian(guardian)}>Edit</button></td></tr>)}</tbody></table>{!data.guardians.length && <p className="py-4 text-sm text-slate-500">No guardian contacts yet.</p>}</div></Card>
          {editor?.kind === "guardian" && <Card title={editor.values?.id ? "Edit guardian" : "Add guardian"} action={<button className={secondary} onClick={() => setEditor(null)}>Cancel</button>}><form key={String(editor.values?.id ?? "new")} className="grid gap-3 sm:grid-cols-2" onSubmit={event => submit(event, form => ({ kind: "guardian", ...(editor.values?.id ? { id: String(editor.values.id) } : {}), firstName: str(form, "firstName"), lastName: str(form, "lastName"), email: str(form, "email"), phone: str(form, "phone") }))}><Field label="First name" name="firstName" defaultValue={String(editor.values?.firstName ?? "")} /><Field label="Last name" name="lastName" defaultValue={String(editor.values?.lastName ?? "")} /><Field label="Email" name="email" type="email" required={false} defaultValue={String(editor.values?.email ?? "")} /><Field label="Phone" name="phone" required={false} defaultValue={String(editor.values?.phone ?? "")} /><button className={primary} disabled={pending}>Save guardian</button></form></Card>}
          <Card title="Student relationships" action={<button className={secondary} onClick={() => setEditor({ kind: "guardian_link" })}>Link guardian</button>}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-2">Student</th><th>Guardian</th><th>Relationship</th><th>Primary</th><th>Legal responsibility</th><th>Action</th></tr></thead><tbody>{data.links.filter(link => matches(name(link.studentId), guardianName(link.guardianId))).map(link => <tr key={link.id} className="border-b border-slate-100"><td className="py-3">{name(link.studentId)}</td><td>{guardianName(link.guardianId)}</td><td>{words(link.relationship)}</td><td>{link.isPrimary ? "Yes" : "No"}</td><td>{link.hasLegalResponsibility ? "Yes" : "No"}</td><td><button className={secondary} onClick={() => editLink(link)}>Edit</button></td></tr>)}</tbody></table>{!data.links.length && <p className="py-4 text-sm text-slate-500">Link a student to a guardian to manage contact responsibility.</p>}</div></Card>
          {editor?.kind === "guardian_link" && <Card title="Guardian relationship" action={<button className={secondary} onClick={() => setEditor(null)}>Cancel</button>}><form key={`${editor.values?.studentId ?? "new"}-${editor.values?.guardianId ?? "new"}`} className="grid gap-3 sm:grid-cols-2" onSubmit={event => submit(event, form => ({ kind: "guardian_link", studentId: str(form, "studentId"), guardianId: str(form, "guardianId"), relationship: str(form, "relationship") as "parent", isPrimary: form.has("isPrimary"), hasLegalResponsibility: form.has("legal") }))}><Select label="Student" name="studentId" choices={studentOptions} defaultValue={String(editor.values?.studentId ?? "")} /><Select label="Guardian" name="guardianId" choices={guardianOptions} defaultValue={String(editor.values?.guardianId ?? "")} /><Select label="Relationship" name="relationship" choices={["parent", "guardian", "foster_carer", "other"].map(value => ({ id: value, name: words(value) }))} defaultValue={String(editor.values?.relationship ?? "parent")} /><div className="flex flex-wrap items-end gap-4 pb-3 text-sm"><label><input type="checkbox" name="isPrimary" defaultChecked={Boolean(editor.values?.isPrimary)} /> Primary contact</label><label><input type="checkbox" name="legal" defaultChecked={Boolean(editor.values?.hasLegalResponsibility)} /> Legal responsibility</label></div><button className={primary} disabled={pending || !studentOptions.length || !guardianOptions.length}>Save relationship</button></form></Card>}</div>}
        {current.id === "attendance" && <div className="space-y-5"><Card title="Submitted roll calls"><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-medium">Class<select className={field} value={selectedAttendanceClass} onChange={event => setAttendanceClass(event.target.value)}><option value="">Choose a class</option>{classOptions.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><form onSubmit={event => { event.preventDefault(); router.push(`/?section=attendance&date=${encodeURIComponent(str(new FormData(event.currentTarget), "date"))}`); }}><Field label="Date" name="date" type="date" defaultValue={date} /><button className={`${secondary} mt-2`} type="submit">Load date</button></form></div><p className="mt-4 text-sm text-slate-600">Teachers submit roll calls. Office staff can correct submitted records with a written explanation.</p><p className="mt-3 text-sm font-semibold">{attendanceSession ? `Roll call: ${words(attendanceSession.status)}` : "No roll call for this class and date."}</p></Card>
          <Card title={`Unexplained absences for ${date}`}>
            <p className="mb-3 text-sm text-slate-600">Absent marks from submitted morning roll calls without a guardian note for this date. Contact the guardian to follow up.</p>
            <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-2">Student</th><th>Class</th><th>Guardian</th><th>Contact</th></tr></thead><tbody>{data.unexplainedAbsences.map(absence => <tr key={absence.studentId} className="border-b border-slate-100"><td className="py-3 font-semibold">{name(absence.studentId)}</td><td>{classLabel(absence.classId)}</td><td>{absence.guardianName ?? "No linked guardian"}</td><td>{absence.phone ? <a className="text-blue-700 underline" href={`tel:${absence.phone}`}>{absence.phone}</a> : absence.email ? <a className="text-blue-700 underline" href={`mailto:${absence.email}`}>{absence.email}</a> : "No contact details"}</td></tr>)}</tbody></table>
              {!data.unexplainedAbsences.length && <p className="py-4 text-sm text-slate-500">No unexplained absences in submitted morning roll calls for this date.</p>}</div>
          </Card>
          <Card title="Guardian absence notes"><p className="mb-3 text-sm text-slate-600">Review a note on its own, or review and excuse the matching absent morning mark in one audited step.</p><div className="space-y-3">{data.absenceNotes.map(note => { const matchingSession = note.absenceDate === date ? data.sessions.find(session => session.period === "morning_roll_call" && session.status === "submitted" && data.records.some(record => record.sessionId === session.id && record.studentId === note.studentId && record.status === "absent")) : undefined; return <article key={note.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3"><div><strong className="text-sm">{name(note.studentId)}</strong><p className="mt-1 text-xs text-slate-600">{note.absenceDate} · {note.reasonCategory.replaceAll("_", " ")} · Guardian: {note.guardianName} {note.guardianLastName}</p><p className="mt-1 text-xs text-slate-500">{words(note.status)}{note.reviewerName ? ` by ${note.reviewerName}` : ""}</p></div>{note.status === "submitted" && <div className="flex flex-wrap gap-2"><button className={secondary} disabled={pending} onClick={() => start(async () => { setMessage(""); const result = await markGuardianAbsenceNoteReviewedAction(note.id); setMessage(result.success ? "Absence note marked reviewed." : result.error); if (result.success) router.refresh(); })}>Review only</button>{matchingSession ? <button className={primary} disabled={pending} onClick={() => start(async () => { setMessage(""); const result = await reviewAndExcuseGuardianAbsenceAction(note.id); setMessage(result.success ? "Absence note reviewed and attendance excused." : result.error); if (result.success) router.refresh(); })}>Review and excuse</button> : note.absenceDate !== date ? <Link className={secondary} href={`/?section=attendance&date=${encodeURIComponent(note.absenceDate)}`}>Load note date</Link> : null}</div>}</article>; })}{!data.absenceNotes.length && <p className="text-sm text-slate-500">No guardian absence notes have been submitted.</p>}</div></Card>
          {attendanceSession && <Card title="Attendance records"><div className="space-y-3">{attendanceRecords.map(record => <form key={record.id} className={`grid items-end gap-3 border-b border-slate-100 pb-3 md:grid-cols-[1fr_170px_1fr_1fr_auto] ${record.status === "absent" || record.status === "late" ? "bg-amber-50/50" : ""}`} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); start(async () => { setMessage(""); const result = await correctOfficeAttendanceAction({ kind: "attendance", classId: attendanceSession.classId, sessionDate: date, studentId: record.studentId, status: str(form, "status") as "present", reason: str(form, "reason"), correctionReason: str(form, "correctionReason") }); setMessage(result.success ? "Attendance correction saved." : result.error); if (result.success) router.refresh(); }); }}><div><strong className="text-sm">{name(record.studentId)}</strong><span className="block text-xs text-slate-500">Previously {words(record.status)}</span></div><Select label="Status" name="status" choices={["present", "absent", "late", "excused"].map(value => ({ id: value, name: words(value) }))} defaultValue={record.status} /><Field label="Attendance reason" name="reason" required={false} defaultValue={record.reason} /><Field label="Correction explanation" name="correctionReason" /><button className={primary} disabled={pending || attendanceSession.status !== "submitted"}>Correct</button></form>)}{!attendanceRecords.length && <p className="text-sm text-slate-500">No student marks recorded in this roll call.</p>}</div></Card>}</div>}
        {current.id === "imports" && <StudentCsvImport role="office_staff" />}
        {current.id === "notices" && <Card title="Published school notices">{notices.map(notice => <article key={notice.id} className="border-b border-slate-100 py-4"><div className="flex justify-between gap-3"><h3 className="font-semibold">{notice.title}</h3><span className="text-xs text-slate-500">{words(notice.priority)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{notice.content}</p></article>)}{!notices.length && <p className="text-sm text-slate-500">No published notices.</p>}</Card>}
      </main></div>
    {showEnrollment && <StudentEnrollmentFlow classes={classOptions.map(item => ({ id: item.id, label: item.name }))}
      existingGuardians={data.guardians.map(item => ({ id: item.id, label: `${item.firstName} ${item.lastName}${item.email ? ` · ${item.email}` : ""}` }))}
      onClose={() => setShowEnrollment(false)} onSaved={message => { setMessage(message); setShowEnrollment(false); }} />}
  </div>;
}
