"use client";

import { useMemo, useState, useTransition, type ComponentType } from "react";
import { useRouter } from "next/navigation";
import { Activity, BellRing, Building2, CheckCircle2, ChevronRight, CircleGauge, Clock3, FileClock,
  LayoutDashboard, LockKeyhole, Menu, Plus, Search, ShieldCheck, UserRoundCheck, UsersRound, X, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AccountSignOut } from "@/components/account-sign-out";
import { createSchoolWithAdminAction, provisionSchoolStaffAction } from "@/app/actions/school-access-actions";
import type { getPlatformInvitationData } from "@/lib/school-invitations";
import type { SystemHealthReport } from "@/lib/monitoring";

type Data = Awaited<ReturnType<typeof getPlatformInvitationData>>;
type Role = "school_admin" | "office_staff" | "teacher" | "safeguarding_lead" | "senco" | "health_nurse";
type Tab = "overview" | "schools" | "access" | "audit" | "security" | "system";
const roles: Role[] = ["school_admin", "office_staff", "teacher", "safeguarding_lead", "senco", "health_nurse"];
const field = "mt-1.5 block h-10 w-full border border-slate-300 bg-white px-3 text-sm placeholder:text-slate-400 focus:border-blue-600";
const panel = "border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04)]";
const nav: { id: Tab; label: string; icon: ComponentType<{ className?: string }> }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "schools", label: "Schools", icon: Building2 },
  { id: "access", label: "Users & access", icon: UsersRound }, { id: "audit", label: "Audit log", icon: FileClock },
  { id: "security", label: "Security", icon: ShieldCheck }, { id: "system", label: "System health", icon: Activity },
];

function roleLabel(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()); }
function relativeTime(value: Date | string | number) {
  const sec = Math.round((new Date(value).getTime() - Date.now()) / 1000); const fmt = new Intl.RelativeTimeFormat("en", { numeric: "auto" });
  if (Math.abs(sec) < 60) return fmt.format(sec, "second"); const min = Math.round(sec / 60);
  if (Math.abs(min) < 60) return fmt.format(min, "minute"); const hour = Math.round(min / 60);
  return Math.abs(hour) < 24 ? fmt.format(hour, "hour") : fmt.format(Math.round(hour / 24), "day");
}
function Pill({ tone, children }: { tone: "green" | "amber" | "red" | "blue" | "slate"; children: React.ReactNode }) {
  const tones = { green: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", amber: "bg-amber-50 text-amber-700 ring-amber-600/20",
    red: "bg-red-50 text-red-700 ring-red-600/20", blue: "bg-blue-50 text-blue-700 ring-blue-600/20", slate: "bg-slate-100 text-slate-600 ring-slate-500/20" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-[11px] font-semibold ring-1 ring-inset ${tones[tone]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{children}</span>;
}
function Metric({ label, value, detail, icon: Icon, tone = "blue" }: { label: string; value: string | number; detail: string; icon: ComponentType<{ className?: string }>; tone?: "blue" | "green" | "amber" | "violet" }) {
  const tones = { blue: "bg-blue-50 text-blue-700", green: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700", violet: "bg-violet-50 text-violet-700" };
  return <article className={`${panel} p-5`}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight tabular-nums">{value}</p></div><span className={`grid h-10 w-10 place-items-center ${tones[tone]}`}><Icon className="h-5 w-5" /></span></div><p className="mt-3 text-xs text-slate-500">{detail}</p></article>;
}
function Heading({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) {
  return <div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 className="font-bold">{title}</h2>{description && <p className="mt-1 text-xs text-slate-500">{description}</p>}</div>{action}</div>;
}
function SearchBox({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) {
  return <div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="h-9 w-64 max-w-[65vw] border border-slate-300 pl-9 pr-3 text-xs" /></div>;
}

export function PlatformInvitations({ data, health }: { data: Data; health: SystemHealthReport }) {
  const [tab, setTab] = useState<Tab>("overview"); const [mobileNav, setMobileNav] = useState(false); const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState(""); const [query, setQuery] = useState(""); const router = useRouter();
  const schoolNames = useMemo(() => new Map(data.schools.map(s => [s.id, s.name])), [data.schools]);
  const uniqueUsers = new Set(data.memberships.map(m => m.userId)).size;
  const activeUsers = new Set(data.memberships.filter(m => m.hasActiveSession).map(m => m.userId)).size;
  const mfaUsers = new Set(data.memberships.filter(m => m.twoFactorEnabled).map(m => m.userId)).size;
  const mfa = uniqueUsers ? Math.round(mfaUsers / uniqueUsers * 100) : 100;
  const passwordChangesDue = new Set(data.memberships.filter(m => m.mustChangePassword).map(m => m.userId)).size;
  const members = data.memberships.filter(m => `${m.name} ${m.phoneNumber ?? ""} ${m.role} ${schoolNames.get(m.organizationId)}`.toLowerCase().includes(query.toLowerCase()));
  const audit = data.audit.filter(e => `${e.action} ${e.actorName ?? "system"} ${e.schoolName} ${e.entityType}`.toLowerCase().includes(query.toLowerCase()));
  function select(next: Tab) { setTab(next); setQuery(""); setMobileNav(false); }
  function run(operation: () => Promise<void>) { setMessage(""); startTransition(async () => { try { await operation(); router.refresh(); } catch { setMessage("The operation could not be completed. Check your connection and retry."); } }); }

  return <div className="min-h-screen bg-slate-50 text-slate-900 lg:grid lg:grid-cols-[248px_1fr]">
    {mobileNav && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-slate-950/40 lg:hidden" onClick={() => setMobileNav(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[248px] flex-col bg-slate-950 text-slate-200 transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${mobileNav ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-18 items-center justify-between border-b border-white/10 px-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center bg-blue-600 text-sm font-extrabold text-white">K</span><div><p className="font-bold text-white">Klassa</p><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-slate-400">Platform console</p></div></div><button aria-label="Close navigation" className="lg:hidden" onClick={() => setMobileNav(false)}><X className="h-5 w-5" /></button></div>
      <nav aria-label="Platform sections" className="flex-1 space-y-1 px-3 py-5"><p className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Operations</p>{nav.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => select(item.id)} className={`flex w-full items-center gap-3 px-3 py-2.5 text-sm font-medium ${tab === item.id ? "bg-blue-600 text-white" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4" /><span className="flex-1 text-left">{item.label}</span>{tab === item.id && <ChevronRight className="h-4 w-4" />}</button>; })}</nav>
      <div className="border-t border-white/10 p-4"><div className="flex items-center gap-3 bg-white/[.04] p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-emerald-500/15 text-emerald-300"><ShieldCheck className="h-4 w-4" /></span><div><p className="text-xs font-semibold text-white">Platform administrator</p><p className="text-[11px] text-slate-500">MFA protected</p></div></div></div>
    </aside>
    <div className="min-w-0"><header className="sticky top-0 z-20 flex h-18 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-6 lg:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="p-2 lg:hidden" onClick={() => setMobileNav(true)}><Menu className="h-5 w-5" /></button><div><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-blue-700">Platform administration</p><h1 className="text-lg font-bold">{nav.find(n => n.id === tab)?.label}</h1></div></div><div className="flex items-center gap-2"><span className="hidden items-center gap-2 border border-slate-200 px-3 py-2 text-xs sm:flex"><span className={`h-2 w-2 rounded-full ${health.status === "healthy" ? "bg-emerald-500" : health.status === "degraded" ? "bg-amber-500" : "bg-red-500"}`} />Systems {health.status}</span><AccountSignOut /></div></header>
      <main className="mx-auto max-w-[1480px] p-4 sm:p-6 lg:p-8">{message && <div role="status" className="mb-5 flex items-center justify-between border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800"><span>{message}</span><button aria-label="Dismiss" onClick={() => setMessage("")}><X className="h-4 w-4" /></button></div>}

        {tab === "overview" && <div className="space-y-6"><Intro title="Platform overview" text="Operational status across every Klassa school. No student records are shown here." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Schools" value={data.schools.length} detail="Provisioned organizations" icon={Building2} /><Metric label="Staff accounts" value={uniqueUsers} detail={`${activeUsers} with an active session`} icon={UsersRound} tone="violet" /><Metric label="MFA coverage" value={`${mfa}%`} detail={`${mfaUsers} of ${uniqueUsers} staff protected`} icon={ShieldCheck} tone="green" /><Metric label="Password changes due" value={passwordChangesDue} detail="Temporary credentials still active" icon={LockKeyhole} tone={passwordChangesDue ? "amber" : "green"} /></div>
          <div className="grid gap-6 xl:grid-cols-[1.45fr_.85fr]"><section className={panel}><Heading title="Recent activity" description="Latest audited changes across the platform" action={<button onClick={() => select("audit")} className="text-xs font-semibold text-blue-700">View audit log</button>} /><div className="divide-y divide-slate-100">{data.audit.slice(0, 7).map(e => <div key={e.id} className="flex gap-3 px-5 py-4"><span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center bg-slate-100"><FileClock className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate text-sm font-semibold">{e.action.replaceAll("_", " ").replaceAll(".", " · ")}</p><time className="text-[11px] text-slate-400">{relativeTime(e.createdAt)}</time></div><p className="mt-1 text-xs text-slate-500">{e.actorName ?? "System"} · {e.schoolName}</p></div></div>)}{!data.audit.length && <Empty text="No audit events recorded yet." />}</div></section>
            <div className="space-y-6"><HealthSummary health={health} onOpen={() => select("system")} /><section className={`${panel} p-5`}><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center bg-blue-50 text-blue-700"><LockKeyhole className="h-5 w-5" /></span><div><h3 className="text-sm font-bold">Tenant boundary protected</h3><p className="mt-1 text-xs text-slate-500">Platform access does not grant access to school records.</p></div></div></section></div></div></div>}

        {tab === "schools" && <div className="space-y-6"><Intro title="School directory" text="Provision schools with their first administrator, then create additional staff accounts directly." /><div className="grid gap-5 xl:grid-cols-2"><CreateSchool pending={pending} run={run} setMessage={setMessage} /><ProvisionStaff data={data} pending={pending} run={run} setMessage={setMessage} /></div>
          <section className={panel}><Heading title="Schools" description="Tenant metadata and platform access at a glance" /><div className="grid gap-px bg-slate-200 md:grid-cols-2 xl:grid-cols-3">{data.schools.map(s => { const schoolMembers = data.memberships.filter(m => m.organizationId === s.id); const setupDue = schoolMembers.filter(m => m.mustChangePassword || !m.twoFactorEnabled).length; return <article key={s.id} className="bg-white p-5"><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center bg-blue-50 font-bold text-blue-700">{s.name.slice(0, 2).toUpperCase()}</span><Pill tone="green">Active</Pill></div><h3 className="mt-4 font-bold">{s.name}</h3><p className="mt-1 text-xs text-slate-500">{s.slug} · {s.timezone}</p><dl className="mt-5 grid grid-cols-2 border-t border-slate-100 pt-4"><SmallStat label="Staff" value={schoolMembers.length} /><SmallStat label="Setup due" value={setupDue} /></dl></article>; })}{!data.schools.length && <Empty text="No schools have been provisioned." />}</div></section></div>}

        {tab === "access" && <div className="space-y-6"><Intro title="Users & access" text="Cross-school membership and authentication posture. Accounts remain scoped to their schools." /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Unique users" value={uniqueUsers} detail={`${data.memberships.length} total memberships`} icon={UsersRound} /><Metric label="Active now" value={activeUsers} detail="Users with an unexpired session" icon={UserRoundCheck} tone="green" /><Metric label="Needs MFA" value={Math.max(0, uniqueUsers - mfaUsers)} detail="Access is blocked until enrollment" icon={LockKeyhole} tone="amber" /></div>
          <section className={panel}><Heading title="Staff directory" description={`${members.length} memberships shown`} action={<SearchBox value={query} onChange={setQuery} placeholder="Search users, roles or schools" />} /><Table headers={["User", "School", "Role", "Security setup", "Session", "Joined"]}>{members.map(m => <tr key={m.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold">{m.name}</p><p className="mt-1 text-xs text-slate-500">{m.phoneNumber ?? "No mobile number"}</p></td><td className="px-5 py-4">{schoolNames.get(m.organizationId)}</td><td className="px-5 py-4"><Pill tone="blue">{roleLabel(m.role)}</Pill></td><td className="px-5 py-4">{m.mustChangePassword ? <Pill tone="amber">Password change due</Pill> : m.twoFactorEnabled ? <Pill tone="green">MFA enabled</Pill> : <Pill tone="amber">MFA required</Pill>}</td><td className="px-5 py-4">{m.hasActiveSession ? <Pill tone="green">Active</Pill> : <span className="text-xs text-slate-500">Offline</span>}</td><td className="px-5 py-4 text-xs text-slate-500">{new Date(m.joinedAt).toLocaleDateString()}</td></tr>)}</Table>{!members.length && <Empty text="No matching staff memberships." />}</section></div>}

        {tab === "audit" && <div className="space-y-6"><Intro title="Platform audit log" text="The latest security-relevant and administrative events across all schools." /><section className={panel}><Heading title="Recent events" description="Showing up to 80 immutable audit entries" action={<SearchBox value={query} onChange={setQuery} placeholder="Search audit events" />} /><Table headers={["Event", "Actor", "School", "Resource", "Time"]}>{audit.map(e => <tr key={e.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-4 font-semibold">{e.action}</td><td className="px-5 py-4">{e.actorName ?? "System"}</td><td className="px-5 py-4">{e.schoolName}</td><td className="px-5 py-4 text-xs text-slate-500">{e.entityType} · {e.entityId.slice(0, 12)}</td><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{relativeTime(e.createdAt)}</td></tr>)}</Table>{!audit.length && <Empty text="No matching audit events." />}</section></div>}

        {tab === "security" && <div className="space-y-6"><Intro title="Security center" text="Authentication coverage, temporary-password exposure, and recent protective controls." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="MFA coverage" value={`${mfa}%`} detail={mfa === 100 ? "All staff are protected" : `${uniqueUsers - mfaUsers} enrollments outstanding`} icon={ShieldCheck} tone={mfa === 100 ? "green" : "amber"} /><Metric label="Active sessions" value={activeUsers} detail="Across all schools" icon={UserRoundCheck} /><Metric label="Rate-limit blocks" value={data.securityEvents.length} detail="Most recent retained events" icon={CircleGauge} tone={data.securityEvents.length ? "amber" : "green"} /><Metric label="Password changes due" value={passwordChangesDue} detail="Users still on temporary credentials" icon={LockKeyhole} tone={passwordChangesDue ? "amber" : "green"} /></div>
          <section className={panel}><Heading title="Recent rate-limit events" description="Requests blocked by platform safeguards" /><div className="divide-y divide-slate-100">{data.securityEvents.map(e => <div key={e.id} className="flex flex-wrap items-center gap-4 px-5 py-4"><span className="grid h-9 w-9 place-items-center bg-amber-50 text-amber-700"><LockKeyhole className="h-4 w-4" /></span><div className="flex-1"><p className="text-sm font-semibold">{e.endpoint}</p><p className="mt-1 text-xs text-slate-500">{e.tier} control · {e.requestCount} requests / {e.limit} allowed</p></div><time className="text-xs text-slate-500">{relativeTime(e.blockedAt)}</time></div>)}{!data.securityEvents.length && <SuccessEmpty title="No recent rate-limit events" text="Platform safeguards have not recorded blocked traffic." />}</div></section></div>}

        {tab === "system" && <div className="space-y-6"><div className="flex items-end justify-between"><Intro title="System health" text="Runtime checks and rolling service telemetry." /><Pill tone={health.status === "healthy" ? "green" : health.status === "degraded" ? "amber" : "red"}>Overall {health.status}</Pill></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Requests · 5 min" value={health.metrics.rollingRequestCount} detail={`${health.metrics.rollingErrorRate}% error rate`} icon={Activity} /><Metric label="Average latency" value={`${health.metrics.averageLatencyMs}ms`} detail="Rolling application response" icon={Clock3} tone="green" /><Metric label="Uptime" value={`${Math.floor(health.uptimeSeconds / 3600)}h`} detail={`${health.environment} · ${health.version}`} icon={CircleGauge} tone="violet" /></div><HealthChecks health={health} /><section className={panel}><Heading title="Active incidents" description="Operational conditions requiring review" />{health.activeIncidents.length ? <div>{health.activeIncidents.map(i => <div key={i.id} className="flex gap-3 border-t border-slate-100 p-5"><BellRing className="h-5 w-5 text-red-600" /><div><p className="font-bold">{i.title}</p><p className="mt-1 text-xs text-slate-600">{i.details}</p></div></div>)}</div> : <SuccessEmpty title="No active incidents" text="All monitored services are operating within configured thresholds." />}</section></div>}
      </main></div>
  </div>;
}

function Intro({ title, text }: { title: string; text: string }) { return <div><h2 className="text-2xl font-bold tracking-tight">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="col-span-full p-8 text-center text-sm text-slate-500">{text}</p>; }
function SuccessEmpty({ title, text }: { title: string; text: string }) { return <div className="flex flex-col items-center px-5 py-12 text-center"><CheckCircle2 className="h-8 w-8 text-emerald-600" /><p className="mt-3 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div>; }
function SmallStat({ label, value }: { label: string; value: number }) { return <div><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 text-lg font-bold tabular-nums">{value}</dd></div>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-semibold uppercase tracking-wider text-slate-500"><tr>{headers.map(h => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function HealthSummary({ health, onOpen }: { health: SystemHealthReport; onOpen: () => void }) { return <section className={panel}><Heading title="System status" description="Live application checks" /><div className="space-y-4 p-5">{Object.entries(health.checks).map(([name, check]) => <div key={name} className="flex items-center justify-between"><span className="flex items-center gap-3 text-sm font-medium capitalize">{check.status === "healthy" ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : <XCircle className="h-4 w-4 text-red-600" />}{name.replaceAll(/([A-Z])/g, " $1")}</span><Pill tone={check.status === "healthy" ? "green" : check.status === "degraded" ? "amber" : "red"}>{check.status}</Pill></div>)}</div><button onClick={onOpen} className="flex w-full items-center justify-between border-t border-slate-200 px-5 py-3 text-xs font-semibold text-blue-700">Open system health <ChevronRight className="h-4 w-4" /></button></section>; }
function HealthChecks({ health }: { health: SystemHealthReport }) { return <section className={panel}><Heading title="Service checks" description={`Last evaluated ${new Date(health.timestamp).toLocaleString()}`} /><div className="grid gap-px bg-slate-200 sm:grid-cols-2">{Object.entries(health.checks).map(([name, check]) => <article key={name} className="bg-white p-5"><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center bg-slate-100">{check.status === "healthy" ? <CheckCircle2 className="h-5 w-5 text-emerald-600" /> : <XCircle className="h-5 w-5 text-red-600" />}</span><Pill tone={check.status === "healthy" ? "green" : check.status === "degraded" ? "amber" : "red"}>{check.status}</Pill></div><h3 className="mt-4 font-bold capitalize">{name.replaceAll(/([A-Z])/g, " $1")}</h3></article>)}</div></section>; }

function CreateSchool({ pending, run, setMessage }: { pending: boolean; run: (op: () => Promise<void>) => void; setMessage: (value: string) => void }) { return <section className={panel}><Heading title="Create a school and administrator" description="Provision the tenant and its first administrator in one step" /><form className="grid gap-4 p-5 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); run(async () => { const result = await createSchoolWithAdminAction({ name: String(values.get("name")), slug: String(values.get("slug")), timezone: String(values.get("timezone")), administratorName: String(values.get("administratorName")), administratorPhone: String(values.get("administratorPhone")), temporaryPassword: String(values.get("temporaryPassword")) }); form.reset(); setMessage(result.accountCreated ? "School and initial administrator created. Share the login phone and temporary password securely." : "School created and the existing Klassa account was added as its administrator. Their existing password was not changed."); }); }}><label className="text-xs font-semibold sm:col-span-2">School name<input name="name" required minLength={2} maxLength={180} className={field} placeholder="Northfield Academy" /></label><label className="text-xs font-semibold">School identifier<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="northfield" maxLength={80} className={field} /></label><label className="text-xs font-semibold">Timezone<input name="timezone" required defaultValue="Atlantic/Reykjavik" className={field} /></label><div className="sm:col-span-2 border-t border-slate-200 pt-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Initial administrator</p></div><label className="text-xs font-semibold sm:col-span-2">Full name<input name="administratorName" required minLength={2} maxLength={180} className={field} /></label><label className="text-xs font-semibold">Login phone<input name="administratorPhone" type="tel" required placeholder="+3545551234" className={field} /></label><label className="text-xs font-semibold">Temporary password<input name="temporaryPassword" type="password" required minLength={12} maxLength={128} autoComplete="new-password" className={field} /></label><p className="text-xs text-slate-500 sm:col-span-2">Give these credentials to the administrator through a secure channel. Klassa forces a password change before MFA enrollment or school access.</p><div className="sm:col-span-2"><Button type="submit" disabled={pending}><Plus className="h-4 w-4" />Create school and administrator</Button></div></form></section>; }
function ProvisionStaff({ data, pending, run, setMessage }: { data: Data; pending: boolean; run: (op: () => Promise<void>) => void; setMessage: (value: string) => void }) { return <section className={panel}><Heading title="Create a staff account" description="Assign access directly without an invitation or SMS" /><form className="grid gap-4 p-5 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); run(async () => { const result = await provisionSchoolStaffAction({ organizationId: String(values.get("school")), administratorName: String(values.get("administratorName")), administratorPhone: String(values.get("administratorPhone")), temporaryPassword: String(values.get("temporaryPassword")), role: String(values.get("role")) as Role }); form.reset(); setMessage(result.accountCreated ? "Staff account created. Share the login phone and temporary password securely." : "The existing Klassa account was added to this school. Their existing password was not changed."); }); }}><label className="text-xs font-semibold sm:col-span-2">School<select name="school" required defaultValue={data.schools[0]?.id ?? ""} className={field}>{!data.schools.length && <option value="">Create a school first</option>}{data.schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-xs font-semibold sm:col-span-2">Full name<input name="administratorName" required minLength={2} maxLength={180} className={field} /></label><label className="text-xs font-semibold">Login phone<input name="administratorPhone" type="tel" required placeholder="+3545551234" className={field} /></label><label className="text-xs font-semibold">School role<select name="role" defaultValue="office_staff" className={field}>{roles.map(r => <option key={r} value={r}>{roleLabel(r)}</option>)}</select></label><label className="text-xs font-semibold sm:col-span-2">Temporary password<input name="temporaryPassword" type="password" required minLength={12} maxLength={128} autoComplete="new-password" className={field} /></label><p className="text-xs text-slate-500 sm:col-span-2">Existing Klassa users keep their current password. New users must replace this temporary password at first sign-in.</p><div className="sm:col-span-2"><Button type="submit" disabled={pending || !data.schools.length}><Plus className="h-4 w-4" />Create staff account</Button></div></form></section>; }
